/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.Minimizar;
import java.awt.GridLayout;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.List;
import java.util.ArrayList;
import javax.swing.*;

/**
 *
 * @author orlando
 */
public class Main extends javax.swing.JFrame {

    private List<String> text;
    private List<JLabel> textBit;
    
    private ArrayList<String> minterminos;
    private ArrayList<String[]>bits;
    
    private Minimizar m;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        text = new ArrayList<>();
        textBit = new ArrayList<>();
        
        minterminos=new ArrayList<>();
        bits = new ArrayList<>();
        //this.setLayout(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabla = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout tablaLayout = new javax.swing.GroupLayout(tabla);
        tabla.setLayout(tablaLayout);
        tablaLayout.setHorizontalGroup(
            tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );
        tablaLayout.setVerticalGroup(
            tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel tabla;
    // End of variables declaration//GEN-END:variables

    void setTabla(int nBits) {
        int t = nBits;
        int g = t+1;
        
        GridLayout g1 = new GridLayout(g,0);
        
        tabla.setLayout(g1);
        tabla.updateUI();
        
        int tFinal = (int)Math.pow(2,t);
        int longT = Integer.toString(tFinal).length();
        for(int i=0;i<tFinal;i++) {
            JLabel nDec = new JLabel(""+i);
            for(int j=0;j<longT;j++) {
                if(nDec.getText().length()<longT) {
                    nDec.setText(" "+nDec.getText());
                }
            }
            
            JTextField S = new JTextField();
            //S.setSize(20, 20);
            S.addKeyListener(new KeyAdapter() {
                public void keyTyped(KeyEvent e) {
                    char caracter = e.getKeyChar();
                    if(caracter!='0'&&caracter!='1'&&caracter!='x'||S.getText().length()==1) {
                        e.consume();
                    }
                }
            });
            
            JLabel nBin = new JLabel();
            String bin = Integer.toBinaryString(i);
            nBin.setText(bin);
            System.out.println(""+i+": "+bin);
            for(int j=0;j<t;j++) {
                if(nBin.getText().length()<t) {
                    nBin.setText("0"+nBin.getText());
                }
            }
            
            
            this.text.add(bin);
            tabla.add(nDec);
            tabla.add(nBin);
            tabla.add(S);
            tabla.updateUI();
        }
    }
}
